import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { getSession } from "@/api/session";
import { Toaster } from "sonner";
import SessionProvider from "@/context/SessionContext";
import ToastProvider from "@/context/ToastContext";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();

  return (
    <html lang="en">
      <body
        className={`${plusJakarta.className} antialiased bg-primary-100/25`}
      >
        <SessionProvider session={session}>
          <ToastProvider>
            {children}
          <Toaster
            toastOptions={{
              classNames: {
                title: "!text-secondary-500",
                success: "!bg-primary-0",
              },
            }}
            duration={3000}
            visibleToasts={6}
            richColors
          />
          </ToastProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
