import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Toaster } from "sonner";
import ToastProvider from "@/context/ToastContext";

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakarta.className} antialiased bg-primary-100/25`}
      >
        <ToastProvider>
          <Header />
          {children}
          <Footer />
          <Toaster
            toastOptions={{
              classNames: {
                title: "!text-secondary-500",
                success: "!bg-primary-0",
              },
            }}
            duration={3000}
            visibleToasts={6}
            richColors
          />
        </ToastProvider>
      </body>
    </html>
  );
}
